// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package schema

import (
	"context"
)

// iteratorForCreateExamQuestions implements pgx.CopyFromSource.
type iteratorForCreateExamQuestions struct {
	rows                 []CreateExamQuestionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateExamQuestions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateExamQuestions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ExamID,
		r.rows[0].Question,
		r.rows[0].Type,
		r.rows[0].Answers,
	}, nil
}

func (r iteratorForCreateExamQuestions) Err() error {
	return nil
}

func (q *Queries) CreateExamQuestions(ctx context.Context, arg []CreateExamQuestionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"exam_questions"}, []string{"exam_id", "question", "type", "answers"}, &iteratorForCreateExamQuestions{rows: arg})
}
