// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: exam_participants.sql

package schema

import (
	"context"

	"github.com/google/uuid"
)

const createExamParticipant = `-- name: CreateExamParticipant :exec
INSERT INTO exam_participants (exam_id, user_id)
VALUES ($1,
        (SELECT (id)
         FROM users
         WHERE email = $2
         LIMIT 1))
ON CONFLICT (user_id , exam_id) DO NOTHING
`

type CreateExamParticipantParams struct {
	ExamID uuid.UUID
	Email  string
}

func (q *Queries) CreateExamParticipant(ctx context.Context, arg CreateExamParticipantParams) error {
	_, err := q.db.Exec(ctx, createExamParticipant, arg.ExamID, arg.Email)
	return err
}
