// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: exams.sql

package schema

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkExamTitleExists = `-- name: CheckExamTitleExists :one
SELECT EXISTS(SELECT 1 FROM exams WHERE title = $1 AND user_id = $2)
`

type CheckExamTitleExistsParams struct {
	Title  string
	UserID pgtype.UUID
}

func (q *Queries) CheckExamTitleExists(ctx context.Context, arg CheckExamTitleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkExamTitleExists, arg.Title, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createExam = `-- name: CreateExam :one
INSERT INTO exams(id , user_id , title , slug , visibility_status , is_accessable,  created_at , updated_at)
VALUES (uuid_generate_v4() , $1 , $2 , $3 , $4 ,$5 ,  current_timestamp , current_timestamp)
RETURNING id, user_id, title, slug, visibility_status, is_accessable, created_at, updated_at
`

type CreateExamParams struct {
	UserID           pgtype.UUID
	Title            string
	Slug             pgtype.Text
	VisibilityStatus string
	IsAccessable     pgtype.Bool
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, createExam,
		arg.UserID,
		arg.Title,
		arg.Slug,
		arg.VisibilityStatus,
		arg.IsAccessable,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.VisibilityStatus,
		&i.IsAccessable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateExamQuestionsParams struct {
	ExamID   pgtype.UUID
	Question string
	Type     string
	Answers  []byte
}

const getExamById = `-- name: GetExamById :one
SELECT id, user_id, title, slug, visibility_status, is_accessable, created_at, updated_at FROM exams WHERE id = $1
`

func (q *Queries) GetExamById(ctx context.Context, id pgtype.UUID) (Exam, error) {
	row := q.db.QueryRow(ctx, getExamById, id)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.VisibilityStatus,
		&i.IsAccessable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExamQuestions = `-- name: GetExamQuestions :many
SELECT id, exam_id, question, answers, type, created_at, updated_at FROM exam_questions WHERE exam_id = $1
`

func (q *Queries) GetExamQuestions(ctx context.Context, examID pgtype.UUID) ([]ExamQuestion, error) {
	rows, err := q.db.Query(ctx, getExamQuestions, examID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExamQuestion
	for rows.Next() {
		var i ExamQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ExamID,
			&i.Question,
			&i.Answers,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserExams = `-- name: GetUserExams :many
SELECT id, user_id, title, slug, visibility_status, is_accessable, created_at, updated_at FROM exams WHERE user_id = $1
`

func (q *Queries) GetUserExams(ctx context.Context, userID pgtype.UUID) ([]Exam, error) {
	rows, err := q.db.Query(ctx, getUserExams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exam
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.VisibilityStatus,
			&i.IsAccessable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
