// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: question_answers.sql

package schema

import (
	"context"

	"github.com/google/uuid"
)

const updateAnswer = `-- name: UpdateAnswer :exec
INSERT INTO question_answers (question_id, user_id, answer)
VALUES ($1, $2, $3)
ON CONFLICT (question_id , user_id) DO UPDATE SET answer = $3
`

type UpdateAnswerParams struct {
	QuestionID uuid.UUID
	UserID     uuid.UUID
	Answer     string
}

func (q *Queries) UpdateAnswer(ctx context.Context, arg UpdateAnswerParams) error {
	_, err := q.db.Exec(ctx, updateAnswer, arg.QuestionID, arg.UserID, arg.Answer)
	return err
}
