// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tokens.sql

package schema

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO tokens(hash , user_id , expiry , scope )
VALUES ( $1 , $2 , $3 , $4 )
RETURNING hash, user_id, expiry, scope
`

type CreateUserTokenParams struct {
	Hash   []byte
	UserID uuid.UUID
	Expiry time.Time
	Scope  string
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createUserToken,
		arg.Hash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	var i Token
	err := row.Scan(
		&i.Hash,
		&i.UserID,
		&i.Expiry,
		&i.Scope,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT users.id,tokens.hash , tokens.expiry  FROM tokens INNER JOIN users ON users.id = tokens.user_id WHERE hash = $1
`

type GetUserByTokenRow struct {
	ID     uuid.UUID
	Hash   []byte
	Expiry time.Time
}

func (q *Queries) GetUserByToken(ctx context.Context, hash []byte) (GetUserByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByToken, hash)
	var i GetUserByTokenRow
	err := row.Scan(&i.ID, &i.Hash, &i.Expiry)
	return i, err
}

const getUserToken = `-- name: GetUserToken :one
SELECT hash, user_id, expiry, scope FROM tokens WHERE hash = $1
`

func (q *Queries) GetUserToken(ctx context.Context, hash []byte) (Token, error) {
	row := q.db.QueryRowContext(ctx, getUserToken, hash)
	var i Token
	err := row.Scan(
		&i.Hash,
		&i.UserID,
		&i.Expiry,
		&i.Scope,
	)
	return i, err
}
