// Code generated by SQLBoiler 4.16.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ExamParticipants string
	ExamQuestions    string
	Exams            string
	GooseDBVersion   string
	Tokens           string
	Users            string
}{
	ExamParticipants: "exam_participants",
	ExamQuestions:    "exam_questions",
	Exams:            "exams",
	GooseDBVersion:   "goose_db_version",
	Tokens:           "tokens",
	Users:            "users",
}
