// Code generated by SQLBoiler 4.16.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ExamParticipants", testExamParticipantsUpsert)

	t.Run("ExamQuestions", testExamQuestionsUpsert)

	t.Run("Exams", testExamsUpsert)

	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)

	t.Run("Tokens", testTokensUpsert)

	t.Run("Users", testUsersUpsert)
}
